language: node_js
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: 
  - greenkeeper-lockfile-update
script:
  - npm run build
  - npm run tslint:check
after_script:
  - greenkeeper-lockfile-upload
