language: node_js
script:
  - npm run build
  - npm run tslint:check
after_success:
  - '[[ $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST_BRANCH = "" ]] &&
    (npm install -g travis-deploy-once && travis-deploy-once "npm run semantic-release")'
